### ISSUE TITLE
Use only single db connection

### ISSUE THREAD

**Issue by michael** [substance/journal#12]
@Integral You require db/index.js multiple times. That could lead to problems, if we have multiple connections to the db. So that's why i was using app.set('db', db) and use only that single db instance. Can we switch back to that approach?

**Comment by Integral** [comment]
@michael, you are right, but I'll manage it some other way... Give me a bit of time. Don't like to wrap every whole module by some function to only pass current app...

**Comment by michael** [comment]
yeh that's not so nice. just didn't have better idea.

**Comment by michael** [comment]
hey u use unix timestamp for created dates? Is that the default format for sqlite? can we somehow convert these when we query for list of users or user object?

**Comment by michael** [comment]
now i did this:

``` js
User.findAll = function(cb) {
  knex.select().table('users')
    .then(function(users) { 
      _.each(users, function(user) {
        user.created_at = new Date(user.created_at);
        user.updated_at = new Date(user.updated_at);
      });
      cb(null, users);
    })
    .catch(cb);
};
```

**Comment by Integral** [comment]
Yes, that's default by knex, so we need to convert on output.

**Comment by Integral** [comment]
I guess it's ok now.
