### ISSUE TITLE
Provide a url /editordev that brings up a demo editor instance with a test article

### ISSUE THREAD

**Issue by michael** [substance/journal#24]
We need this because once we connect to the server API we need to click around to actually get to the editor. This will be annoying during editor dev so we provide a shortcut that also doesn't care about authentication etc. (this url is only available in dev mode).

**Comment by Integral** [comment]
What's the problem? Or you want to use api for that?

**Comment by michael** [comment]
no problems.. just a convenience thing.. i will take care of that.

**Comment by michael** [comment]
We don't need this I think, because now we have a simple router in place, so we can easily reload the current doc during development.
