### ISSUE TITLE
Do automatic logout when invalid token is provided

### ISSUE THREAD

**Issue by michael** [substance/journal#26]
Currently we stay logged in but receive errors from the api. Maybe we should poll every few seconds if the login token is still valid.

**Comment by Integral** [comment]
maybe just provide automatic redirect?

**Comment by michael** [comment]
There could be unsaved changes of a document when this happens. we somehow need to solve this session expire thing. I will have idea.. but needs more thinking.

**Comment by michael** [comment]
We have an async initialBackend mechanism now that resets the session of the token is outdated. So this is fixed.
