### ISSUE TITLE
No checkToken for GET /documents/:doc

### ISSUE THREAD

**Issue by michael** [substance/journal#32]
In the front end (Reader) I need to be able to access the `GET /documents/:doc` service without authentication. However we need some proper permission logic here.. other than just checking if the user is logged in.

Send result when: 
- document has published_on property set (not null)
- user is logged in (every user is an admin)
- (in future: only document owner or collaborator have access)

For now i just disabled checkToken, but we must fix this.

**Comment by Integral** [comment]
not sure that i understand,you said without authentication, but in the same
time user must be logged in...

**Comment by michael** [comment]
only published docs you should be able to load when not logged in, all draft docs require authentication.

A doc is published if published_on field is set, it's null for draft documents.

Do you have time to implement this in the next days? I'm pretty much done with the reader and now i would try to complete the publishing workflow.

**Comment by Integral** [comment]
Yep
