### ISSUE TITLE
More flexible Document.findAll

### ISSUE THREAD

**Issue by michael** [substance/journal#34]
Allow parameters for finding documents.
- change name from `findAll` to `find`
- allow param published (true|false)

For example i want to get all published docs:

``` js
Document.find({published: true}, function(e, docs));
```

@Integral you have time for that in the next days?

**Comment by michael** [comment]
Also we would need to get the users fullname for the document record for that function. Can you also add that?

**Comment by Integral** [comment]
Yep, I'll do it.

**Comment by Integral** [comment]
Note that landing page will show you only published docs, because you not sending token
